[tool.poetry]
name = "Exist Client"
version = "0.1.0"
description = ""
authors = ["Ilya Nekhay <nekhayiv@gmail.com>"]
readme = "README.md"
packages = [{include = "exist_client", from = "src"}]



[tool.poetry.dependencies]
python = "^3.10"



[tool.poetry.group.dev.dependencies]
# Code management
pre-commit = "*"

# Testing
pytest = "*"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
