# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# https://github.com/codecov/codecov-action
# https://github.com/snok/install-poetry
# https://github.com/marketplace/actions/pypi-publish

name: Publish to PyPI
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  call-cicd:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  publish:
    needs: call-cicd
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/exist-client
    permissions:
      id-token: write
    steps:
      - name: 'Download Build'
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
